#!/bin/sh /etc/rc.common

USE_PROCD=1

start_service() {
	local enabled

	config_load 'esp'
	config_get enabled general 'enable' '0'

	

	if [ "$enabled" -eq 1 ]; then
		procd_open_instance
		procd_set_param command /usr/bin/esp_launcher
		procd_set_param pidfile /var/run/esp.pid
		procd_set_param file /etc/config/esp
		procd_close_instance
	fi
}

service_triggers() {
	procd_add_reload_trigger "esp"
}

reload_service() {
	stop
	start
}
